services:

  euro-office:
    image: ghcr.io/euro-office/documentserver:latest
    container_name: euro-office
    stdin_open: true
    tty: true
    ports:
      - "8500:80"
    restart: unless-stopped
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=my_secret
