services:

  euro-office:
    image: ghcr.io/euro-office/documentserver:latest
    container_name: euro-office
    stdin_open: true
    tty: true
    ports:
      - "8500:80"
    restart: unless-stopped
    environment:
      - EXAMPLE_ENABLED=true
      - JWT_SECRET=dCYlN0UjXA0sO4lQaz0JxMd11U1c0lausHwKrW1Jat8=
      - THEME=euro-office
